name: restaubook
description: A new Flutter project.

# Prevent the package from being accidentally published to pub.dev.
publish_to: 'none' 

# Application version and build number.
version: 1.0.0+1

# Dart SDK version required.
environment:
  sdk: '>=3.5.4 <4.0.0'

# Dependencies required for the application.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  flutter_email_sender: ^6.0.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  
# Development dependencies.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  font_awesome_flutter: ^10.8.0

  

# Flutter-specific settings.
flutter:
  uses-material-design: true

  # Define the assets used in the application.
  assets:
    - images/
    - images/dar.jpg
    - images/lao.jpg
    - images/passage.jpg
    - images/category_0.png
    - images/category_1.png
    - images/category_2.png
    - images/category_3.png
    - images/category_4.png
    - images/category_5.png
    - images/category_6.png
    - images/category_7.png








